// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4EAaM78f395z3f2zlnivGwJ8h7XIMglA',
    appId: '1:398512212810:web:e79a105c0ee44256ad0fb3',
    messagingSenderId: '398512212810',
    projectId: 'login-e5f9b',
    authDomain: 'login-e5f9b.firebaseapp.com',
    databaseURL: 'https://login-e5f9b-default-rtdb.firebaseio.com',
    storageBucket: 'login-e5f9b.firebasestorage.app',
    measurementId: 'G-YW2BG4CM8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD23vGlWliK2c71j0cJk0fxZqfbQet_bkI',
    appId: '1:398512212810:android:978340db6158507cad0fb3',
    messagingSenderId: '398512212810',
    projectId: 'login-e5f9b',
    databaseURL: 'https://login-e5f9b-default-rtdb.firebaseio.com',
    storageBucket: 'login-e5f9b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkvgVx49Cdxnqq0A_efbg-_OCCjfsyoQA',
    appId: '1:398512212810:ios:f203fb35f3a62dbead0fb3',
    messagingSenderId: '398512212810',
    projectId: 'login-e5f9b',
    databaseURL: 'https://login-e5f9b-default-rtdb.firebaseio.com',
    storageBucket: 'login-e5f9b.firebasestorage.app',
    iosClientId: '398512212810-c888mb1q408hlbe58iausds0mbmgioed.apps.googleusercontent.com',
    iosBundleId: 'com.livechat.app',
  );
}
